### ISSUE TITLE
Does this plugin still work on Moodle 3.9?

### ISSUE THREAD

**Issue by toza-mimoza** [jmvedrine/moodle-qformat_imsqti21#1]
Hi, I am interested in this plugin and would like to maintain it, but I am not sure if it would work on newer versions such as version 3.9. 

Edit: 

Plugin installs without errors on this version but **breaks** Import and Export tabs for Question bank. They are both not accessible anymore.

**Comment by jmvedrine** [comment]
Hello,
As I wrote in the readme I am now completely retired and unable to do anything concerning Moodle development .I don't even have a Moodle install and no development tools on my computer anymore !)
The best advice I can give is to post in the Moodle forum to see if Tim Hunt or anybody else can help to upgrade this plugin for Moodle recent versions. Alternatively you can look at the recent changes done in other qformat plugins. Maybe there is not a lot of work to do but I don't really know.

**Comment by jmvedrine** [comment]
Sorry I just checked and it seems that contrary to other of my repositories I fogot to add a note in the readme of this one to report that I am now retired so you couldn't be aware of that !

**Comment by toza-mimoza** [comment]
That's perfectly fine Mr Vedrine, enjoy your retirement. If I manage to repair the codebase to work on the newest version of Moodle I'll let you know. Posting on the moodle forum is an excellent idea. Thanks for your reply.
